name: Build & Release APK

on:
  pull_request:
    branches:
      - main
      - master

  push:
    branches:
      - main
      - master
      - develop

jobs:
  build:
    name: Build Flutter APK
    runs-on: windows-latest

    steps:
      # Checkout project
      - name: Checkout Code
        uses: actions/checkout@v4

      # Setup Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.9'
          channel: 'stable'

      # Install dependencies
      - name: Install Packages
        run: flutter pub get

      # Check Flutter
      - name: Flutter Doctor
        run: flutter doctor

      # Build Release APK
      - name: Build APK
        run: flutter build apk --release --split-per-abi

      # Upload APK Artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/*.apk

      # Create GitHub Release
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/app/outputs/flutter-apk/*.apk
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
